In [3]:
import pymysql
import pymysql.cursors
import pandas as pd

In [8]:
connection = pymysql.connect(host='pharmatlas.cdpqztjopq7f.us-east-1.rds.amazonaws.com',
                             user='pharmatlas',
                             password='1XcBD6MWxJ',
                             db='pharmatlas_v2',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

In [9]:
with connection.cursor() as c:
    sql = "select nct_id, id from CT"
    c.execute(sql)
    clinical_trials_ids = pd.DataFrame(c.fetchall())
clinical_trials_ids.head()

    id       nct_id
0  102  NCT00000102
1  104  NCT00000104
2  105  NCT00000105
3  106  NCT00000106
4  107  NCT00000107

In [10]:
with connection.cursor() as c:
    sql = "select * from CT_has_Drug"
    c.execute(sql)
    clinical_trials_has_drug = pd.DataFrame(c.fetchall()).assign(drug_id=lambda d: d.Pubchem_id)
clinical_trials_has_drug.head()

    CT_id  Pubchem_id     id  drug_id
0    2963         137   2926      137
1    2975         137   2937      137
2   54171         137   8511      137
3  524485         137  23932      137
4  571558         137  25396      137

In [7]:
drugs = pd.read_csv('../data/clinicaltrials/intermediate/pharmatlas_v2_Drug.csv')
drugs.head()

,id,pubchem_id,elements,atoms,bonds,charge,molecular_formula,molecular_weight,canonical_smiles,isomeric_smiles,...,defined_atom_stereo_count,undefined_atom_stereo_count,bond_stereo_count,defined_bond_stereo_count,undefined_bond_stereo_count,covalent_unit_count,name,tmp_cumror,tmp_ror50,tmp_num_side_effects
0,24841,137,NaN,NaN,NaN,0,C5H9NO3,131.1300,C(CC(=O)O)C(=O)CN,C(CC(=O)O)C(=O)CN,...,0,0,0,0,0,1,Aminolevulinic acid,5.16631,35.9099,1
1,28632,177,NaN,NaN,NaN,0,C2H4O,44.0526,CC=O,CC=O,...,0,0,0,0,0,1,Aldehyde,0.00000,0.0000,0
2,30317,178,NaN,NaN,NaN,0,C2H5NO,59.0672,CC(=O)N,CC(=O)N,...,0,0,0,0,0,1,Acetamide,0.00000,0.0000,0
3,13648,200,NaN,NaN,NaN,0,C9H15N4O8P,338.2110,C1=NC(=C(N1C2C(C(C(O2)COP(=O)(O)O)O)O)N)C(=O),C1=NC(=C(N1C2C(C(C(O2)COP(=O)(O)O)O)O)N)C(=O),...,0,4,0,0,0,1,Zmp,0.00000,0.0000,0
4,14068,204,NaN,NaN,NaN,0,C4H6N4O3,158.1150,C1(C(=O)NC(=O)N1)NC(=O)N,C1(C(=O)NC(=O)N1)NC(=O)N,...,0,1,0,0,0,1,Allantoin,0.00000,0.0000,0

In [12]:
clinical_studies = pd.read_csv('../data/clinicaltrials/intermediate/clinicaltrials/clinical_study.csv')
print(clinical_studies.shape, clinical_studies.columns)
clinical_studies.head()

(186941, 45) Index(['acronym', 'biospec_descr', 'biospec_retention', 'brief_summary',
       'brief_title', 'completion_date', 'completion_date_type', 'criteria',
       'detailed_description', 'download_date', 'download_date_dt',
       'enrollment', 'enrollment_type', 'firstreceived_date',
       'firstreceived_results_date', 'gender', 'has_dmc',
       'has_expanded_access', 'healthy_volunteers', 'is_fda_regulated',
       'is_section_801', 'lastchanged_date', 'limitations_and_caveats',
       'maximum_age', 'minimum_age', 'nct_id', 'number_of_arms',
       'number_of_groups', 'official_title', 'org_study_id', 'overall_status',
       'phase', 'primary_completion_date', 'primary_completion_date_type',
       'sampling_method', 'source', 'start_date', 'study_design', 'study_pop',
       'study_rank', 'study_type', 'target_duration', 'url',
       'verification_date', 'why_stopped'],
      dtype='object')

,acronym,biospec_descr,biospec_retention,brief_summary,brief_title,completion_date,completion_date_type,criteria,detailed_description,download_date,...,source,start_date,study_design,study_pop,study_rank,study_type,target_duration,url,verification_date,why_stopped
0,NaN,NaN,NaN,This study will test the ability of extended r...,Congenital Adrenal Hyperplasia: Calcium Channe...,NaN,NaN,Inclusion Criteria:\n\n - diagnosed ...,This protocol is designed to assess both acute...,ClinicalTrials.gov processed this data on Marc...,...,National Center for Research Resources (NCRR),NaN,"Intervention Model: Parallel Assignment, Maski...",NaN,74274,Interventional,NaN,http://clinicaltrials.gov/show/NCT00000102,January 2004,NaN
1,NaN,NaN,NaN,Inner city children are at an increased risk f...,Does Lead Burden Alter Neuropsychological Deve...,NaN,NaN,Inclusion Criteria:\n\n - Pregnant m...,NaN,ClinicalTrials.gov processed this data on Marc...,...,National Center for Research Resources (NCRR),NaN,"Observational Model: Defined Population, Time ...",NaN,133424,Observational,NaN,http://clinicaltrials.gov/show/NCT00000104,December 2003,NaN
2,NaN,analysis of blood samples before and 4 weeks p...,Samples With DNA,The purpose of this study is to learn how the ...,Vaccination With Tetanus and KLH to Assess Imm...,March 2012,Actual,Inclusion Criteria:\n\n - Patients m...,Patients will receive each vaccine once only c...,ClinicalTrials.gov processed this data on Marc...,...,"Masonic Cancer Center, University of Minnesota",July 2002,"Observational Model: Case Control, Time Perspe...",- Normal volunteers\n\n - Patients ...,22675,Observational,NaN,http://clinicaltrials.gov/show/NCT00000105,November 2012,Replaced by another study.
3,NaN,NaN,NaN,Recently a non-toxic system for whole body hyp...,41.8 Degree Centigrade Whole Body Hyperthermia...,NaN,NaN,Inclusion Criteria:\n\n - Patients a...,NaN,ClinicalTrials.gov processed this data on Marc...,...,National Center for Research Resources (NCRR),NaN,"Allocation: Randomized, Intervention Model: Pa...",NaN,17221,Interventional,NaN,http://clinicaltrials.gov/show/NCT00000106,November 2000,NaN
4,NaN,NaN,NaN,Adults with cyanotic congenital heart disease ...,Body Water Content in Cyanotic Congenital Hear...,NaN,NaN,Inclusion Criteria:\n\n - Resting bl...,NaN,ClinicalTrials.gov processed this data on Marc...,...,National Center for Research Resources (NCRR),NaN,Observational Model: Case Control,NaN,122842,Observational,NaN,http://clinicaltrials.gov/show/NCT00000107,December 2003,NaN

In [28]:
clinical_studies['nct_id'] = clinical_studies['nct_id'].str.strip('\n')

In [14]:
interventions = pd.read_csv('../data/clinicaltrials/intermediate/clinicaltrials/interventions.csv')
interventions.head()

,description,intervention_id,intervention_name,intervention_type,nct_id
0,Tablets twice daily for 8 days\nDose level 5,24,Placebo,Drug,NCT00697281
1,A NON INTERVENTIONAL OBSERVATIONAL STUDY:\nDos...,26,activated recombinant human factor VII,Drug,NCT00697320
2,MLN8237 administered twice daily (BID) on Days...,28,MLN8237,Drug,NCT00697346
3,NaN,31,Interleukin-12,Drug,NCT00005779
4,(2) 500mg tablets taken by mouth every 6-8 hours,33,Cyclokapron,Drug,NCT00697385

In [15]:
sponsors = pd.read_csv('../data/clinicaltrials/intermediate/clinicaltrials/sponsors.csv')
sponsors.head()

,agency,agency_class,nct_id,sponsor_id,sponsor_type
0,National Institute on Drug Abuse (NIDA),NIH,NCT00000204,1,Collaborator
1,National Institute on Drug Abuse (NIDA),NIH,NCT00000205,2,Lead Sponsor
2,National Institute on Drug Abuse (NIDA),NIH,NCT00000206,3,Lead Sponsor
3,National Institute on Drug Abuse (NIDA),NIH,NCT00000207,4,Lead Sponsor
4,National Institute on Drug Abuse (NIDA),NIH,NCT00000208,5,Lead Sponsor

In [16]:
clinical_trials_has_drug.shape

(62757, 4)

In [17]:
ct_drugs = (
            clinical_trials_has_drug
            .drop(['id', 'Pubchem_id'], axis=1)
            .merge(drugs
                   .rename(columns=dict(name='drug_name'))
                   .assign(drug_name=lambda d: d.drug_name.str.replace(';', ','))
                   , how='inner', left_on='drug_id', right_on='pubchem_id')
            [['CT_id', 'pubchem_id', 'drug_name']]
            .groupby('CT_id')
            .agg(dict(
                pubchem_id=lambda ids: ';'.join(map(str, ids)),
                drug_name=';'.join
            ))
            .reset_index()
        )
ct_drugs.head()

   CT_id                drug_name    pubchem_id
0    102               Nifedipine          4485
1    114  Vitamin e;Phylloquinone  2116;5280483
2    115            Acetazolamide          1986
3    116        Vitamin e;Retinol   2116;445354
4    120             Erythromycin         12560

In [37]:
ct_sponsors = (
    clinical_trials_ids
    .merge(sponsors, on='nct_id')
    [['nct_id', 'agency']]
#     .groupby('nct_id')
#     .agg({'agency': ';'.join})
    .reset_index()
)
ct_sponsors.head()

   index       nct_id                                          agency
0      0  NCT00000102   National Center for Research Resources (NCRR)
1      1  NCT00000104   National Center for Research Resources (NCRR)
2      2  NCT00000104           HRSA/Maternal and Child Health Bureau
3      3  NCT00000105  Masonic Cancer Center, University of Minnesota
4      4  NCT00000106   National Center for Research Resources (NCRR)

In [68]:
(
    clinical_studies
    .merge(clinical_trials_ids)
    .merge(
        ct_drugs, how='inner', left_on='id', right_on='CT_id'
    )
    .merge(ct_sponsors, on='nct_id')
    
    [['nct_id', 
      'brief_title', 
      'detailed_description', 
      'overall_status', 
#       'source', 
      'start_date', 
#       'is_fda_regulated',
      'phase',
      'completion_date',
      'drug_name',
      'pubchem_id',
      'agency'
     ]]
#     .head()
    .to_csv('../data/clinicaltrials/clinicaltrials-phase-no-na-drugs.agg.csv', index=False)
#     .query('nct_id == "NCT00000125"')
#     .drug_name
#     .shape
)

,nct_id,brief_title,detailed_description,overall_status,start_date,phase,completion_date,drug_name,pubchem_id,agency
0,NCT00000102,Congenital Adrenal Hyperplasia: Calcium Channe...,This protocol is designed to assess both acute...,Completed,NaN,Phase 1/Phase 2,NaN,Nifedipine,4485,National Center for Research Resources (NCRR)
1,NCT00000114,Randomized Trial of Vitamin A and Vitamin E Su...,Retinitis pigmentosa (RP) is a group of inheri...,Completed,May 1984,Phase 3,June 1987,Vitamin e;Phylloquinone,2116;5280483,National Eye Institute (NEI)
2,NCT00000115,Randomized Trial of Acetazolamide for Uveitis-...,"Uveitis, an intraocular inflammatory disease, ...",Completed,December 1990,Phase 2,June 1994,Acetazolamide,1986,National Eye Institute (NEI)
3,NCT00000116,Randomized Trial for Retinitis Pigmentosa,Retinitis pigmentosa (RP) is a group of inheri...,Completed,May 1996,Phase 3,September 1997,Vitamin e;Retinol,2116;445354,National Eye Institute (NEI)
4,NCT00000120,Clinical Trial of Eye Prophylaxis in the Newborn,Sexually transmitted diseases are a major caus...,Completed,January 1985,Phase 3,NaN,Erythromycin,12560,National Eye Institute (NEI)

In [167]:
(
    clinical_trials_has_drug.drop(['id', 'Pubchem_id'], axis=1)
    .merge(clinical_trials_ids, left_on='CT_id', right_on='id')
    .drop(['id', 'CT_id'], axis=1)
    .rename(columns={'drug_id': 'pubchem_id'})
    .to_csv('../data/clinicaltrials/intermediate/clinicaltrials/clinical_trials_drugs.csv', index=False)
)